### ISSUE TITLE
NPM Error

### ISSUE THREAD

**Issue by kevinlove** [rafelafrance/nfn-listener#1]
klove@reports:~/nfn-listener$ npm start

> nfn-listener@0.1.0 start /home/klove/nfn-listener
> node .

/home/klove/nfn-listener/nfn-listener.js:12
const pusherObservable = () => {
                          ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

**Comment by rafelafrance** [comment]
What version of node are you using?

**Comment by kevinlove** [comment]
v0.10.47

**Comment by rafelafrance** [comment]
I made some changes to the code to try and help with this. However, 0.10.47 is really old, so you may have to upgrade to version 4.6.0 (LTS) to get the needed libs to work.

**Comment by kevinlove** [comment]
No dice.

klove@reports:~/nfn-listener$ git pull
Already up-to-date.
klove@reports:~/nfn-listener$ node --version
v4.6.0
klove@reports:~/nfn-listener$ npm start

> nfn-listener@0.1.0 start /home/klove/nfn-listener
> node .


/home/klove/nfn-listener/nfn-listener.js:14
  socket.subscribe(channelName).bind(eventName, data => { msg.onNext(data); })
                                                      ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

**Comment by rafelafrance** [comment]
All "=>" function calls are gone.
